name: CD - Deploy 🚀

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Image version (v1, v2...)"
        required: true

jobs:
  deploy:
    runs-on: [self-hosted, Windows, X64]

    steps:
      # 1️⃣ Checkout
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2️⃣ Check Docker
      - name: Check Docker
        run: docker ps

      # 3️⃣ Login to JFrog
      - name: Docker Login
        run: |
          docker login trialuy8zrn.jfrog.io `
          -u ${{ secrets.JFROG_USERNAME }} `
          -p ${{ secrets.JFROG_TOKEN }}

      # 4️⃣ Pull Selected Version ✅
      - name: Pull Image
        run: |
          docker pull trialuy8zrn.jfrog.io/docker-trial/myapp:${{ github.event.inputs.version }}

      # 5️⃣ Stop Old Container
      - name: Stop Old Container
        shell: powershell
        run: |
          $container = docker ps -a -q -f name=myapp-container
          if ($container) {
            docker stop myapp-container
            docker rm myapp-container
          } else {
            Write-Output "No container found"
          }

      # 6️⃣ Run NEW VERSION ✅
      - name: Run Container
        run: |
          docker run -d -p 8000:80 --name myapp-container `
          trialuy8zrn.jfrog.io/docker-trial/myapp:${{ github.event.inputs.version }}

      # 7️⃣ Verify
      - name: Verify
        run: docker ps