name: CI - Build & Push 🚀

on:
  push:
    branches:
      - main

env:
  REGISTRY: trialuy8zrn.jfrog.io/docker-trial
  IMAGE_NAME: myapp

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      # Checkout
      - name: Checkout Code
        uses: actions/checkout@v4

      # Build Docker Image
      - name: Build Image
        run: |
          docker build -t myapp .

      # Login to JFrog
      - name: Docker Login
        run: |
          echo ${{ secrets.JFROG_TOKEN }} | docker login trialuy8zrn.jfrog.io \
          -u ${{ secrets.JFROG_USERNAME }} --password-stdin

      # Tag Image
      - name: Tag Image
        run: |
          docker tag myapp $REGISTRY/$IMAGE_NAME:${{ github.sha }}
          docker tag myapp $REGISTRY/$IMAGE_NAME:latest

      # Push Image
      - name: Push Image
        run: |
          docker push $REGISTRY/$IMAGE_NAME:${{ github.sha }}
          docker push $REGISTRY/$IMAGE_NAME:latest