name: Deploy Static website

on:
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build docker image 
        run: docker build -tmy-app .

      - name: Run Container ( test )  
        run: docker run -d -p 8080:80 my-app
       

