name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-upload-deploy:
    runs-on: ubuntu-latest

    steps:
      #  Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v4

      #  Verify dist exists
      - name: Check dist folder
        run: ls -la dist

      #  Install JFrog CLI
      - name: Install JFrog CLI
        run: curl -fL https://getcli.jfrog.io | sh

      #  Configure JFrog
      - name: Configure JFrog
        run: |
          ./jfrog config add my-server \
          --url=${{ secrets.JFROG_URL }} \
          --user=${{ secrets.JFROG_USERNAME }} \
          --apikey=${{ secrets.JFROG_TOKEN }} \
          --interactive=false

      #  Upload Artifact to JFrog
      - name: Upload dist to JFrog
        run: |
         ./jfrog rt u "dist/*" docker-trial/ --server-id=my-server

      #  Build Docker Image
      - name: Build Docker Image
        run: docker build -t myapp .

      #  Login to JFrog Docker Registry
      - name: Docker Login
        run: |
          echo ${{ secrets.JFROG_TOKEN }} | docker login https://trialuy8zrn.jfrog.io \
          -u ${{ secrets.JFROG_USERNAME }} --password-stdin

      #  Tag Docker Image
      - name: Tag Image
        run: |
          docker tag myapp trialuy8zrn.jfrog.io/docker-trial/myapp:latest
          # don't use https:// url while tag or push docker img --aaksh

      # Push Docker Image
      - name: Push Image
        run: |
          docker push trialuy8zrn.jfrog.io/docker-trial/myapp:latest
